# Generated by Django 5.0.7 on 2024-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
    ]
