# Generated by Django 5.0.7 on 2024-08-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
